import { jsPDF } from "jspdf";

const RISK_RGB = {
  Low:      [22,  163, 74],
  Medium:   [217, 119, 6],
  High:     [220, 38,  38],
  Critical: [127, 29,  29],
};

const RECOMMENDATIONS = {
  Low:      ["Normal activities are safe.", "Stay hydrated — drink 2–3L of water.", "Use sunscreen if outdoors for long periods."],
  Medium:   ["Avoid outdoor activity between 11am–3pm.", "Drink water every 30 minutes.", "Wear a hat, sunglasses, and light clothing.", "Check on elderly neighbours."],
  High:     ["Stay indoors as much as possible.", "Drink 4–5L of water daily.", "Never leave children or pets in cars.", "Watch for heat exhaustion symptoms.", "Use fans or air conditioning."],
  Critical: ["Do NOT go outside.", "Drink 5–6L of water throughout the day.", "Call emergency services if feeling unwell.", "Close blinds to block heat.", "Check on vulnerable people nearby."],
};

function sectionHeader(doc, label, y, pageW) {
  doc.setFillColor(21, 101, 192);
  doc.rect(14, y, pageW - 28, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(label, 18, y + 5.5);
  doc.setTextColor(31, 41, 55);
  doc.setFont("helvetica", "normal");
  return y + 13;
}

function kv(doc, label, value, x, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(label.toUpperCase(), x, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(31, 41, 55);
  doc.text(String(value), x, y + 5);
  return y + 13;
}

export default function DownloadReport({ weather }) {
  const handleDownload = async () => {
    const doc   = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    let   y     = 0;

    const city    = weather?.city                 ?? "N/A";
    const temp    = weather?.temperature          ?? "N/A";
    const hum     = weather?.humidity             ?? "N/A";
    const rain    = weather?.rainfall             ?? "N/A";
    const wind    = weather?.wind_speed           ?? "N/A";
    const risk    = weather?.heat_risk            ?? "N/A";
    const cond    = weather?.weather_description  ?? "N/A";
    const nino    = weather?.el_nino_status       ?? "N/A";
    const conf    = weather?.heat_risk_confidence ?? "N/A";
    const expl    = weather?.heat_risk_explanation ?? "";
    const now     = new Date();

    // ── HEADER ──────────────────────────────────────────────
    doc.setFillColor(13, 71, 161);
    doc.rect(0, 0, pageW, 36, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("Satellite-Based El Niño Heat Monitoring System", pageW / 2, 13, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("AI-Powered Heat Risk Report", pageW / 2, 20, { align: "center" });

    doc.setFontSize(9);
    doc.setTextColor(186, 230, 253);
    doc.text(`City: ${city}   |   ${now.toLocaleString()}   |   Generated by AI`, pageW / 2, 28, { align: "center" });

    y = 44;

    // ── SECTION 1: CURRENT WEATHER ───────────────────────────
    y = sectionHeader(doc, "1. CURRENT WEATHER CONDITIONS", y, pageW);

    const col1 = 14, col2 = pageW / 2 + 4;
    kv(doc, "Temperature",       `${temp}°C`,  col1, y);
    kv(doc, "Humidity",          `${hum}%`,    col2, y);
    y += 13;
    kv(doc, "Rainfall",          `${rain} mm`, col1, y);
    kv(doc, "Wind Speed",        `${wind} km/h`, col2, y);
    y += 13;
    kv(doc, "Weather Condition", cond,         col1, y);
    kv(doc, "El Niño Status",    nino,         col2, y);
    y += 16;

    // ── SECTION 2: HEAT RISK ASSESSMENT ─────────────────────
    y = sectionHeader(doc, "2. HEAT RISK ASSESSMENT", y, pageW);

    const rgb = RISK_RGB[risk] || [107, 114, 128];
    doc.setFillColor(...rgb);
    doc.roundedRect(14, y, 60, 14, 3, 3, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(`${risk} Risk`, 44, y + 9, { align: "center" });

    doc.setTextColor(31, 41, 55);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Confidence: ${conf}%`, 82, y + 9);
    y += 20;

    if (expl) {
      const lines = doc.splitTextToSize(expl, pageW - 28);
      doc.setFontSize(10);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 6;
    }

    // ── SECTION 3: AI RECOMMENDATION ────────────────────────
    y = sectionHeader(doc, "3. AI RECOMMENDATION", y, pageW);

    const recs = RECOMMENDATIONS[risk] || RECOMMENDATIONS.Low;
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    recs.forEach((rec) => {
      doc.text(`•  ${rec}`, 18, y);
      y += 6;
    });
    y += 6;

    // ── FETCH 7-DAY FORECAST ─────────────────────────────────
    let forecast = [];
    try {
      const r = await fetch(`http://127.0.0.1:5000/heatforecast?city=${encodeURIComponent(city)}`);
      const d = await r.json();
      forecast = d.forecast || [];
    } catch (_) { /* skip if unavailable */ }

    // ── SECTION 4: ANALYTICS SUMMARY ────────────────────────
    if (forecast.length > 0) {
      y = sectionHeader(doc, "4. ANALYTICS SUMMARY (7-DAY)", y, pageW);

      const temps  = forecast.map((d) => d.temperature);
      const humids = forecast.map((d) => d.humidity   ?? 0);
      const winds  = forecast.map((d) => d.wind_speed ?? 0);
      const avg    = (arr) => (arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(1);

      const summaryItems = [
        ["Highest Temp",    `${Math.max(...temps)}°C`],
        ["Lowest Temp",     `${Math.min(...temps)}°C`],
        ["Avg Temperature", `${avg(temps)}°C`],
        ["Avg Humidity",    `${avg(humids)}%`],
        ["Avg Wind Speed",  `${avg(winds)} km/h`],
      ];

      const colW = (pageW - 28) / summaryItems.length;
      summaryItems.forEach(([label, val], i) => {
        const x = 14 + i * colW;
        doc.setFillColor(241, 245, 249);
        doc.rect(x, y, colW - 2, 16, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(31, 41, 55);
        doc.text(val, x + (colW - 2) / 2, y + 7, { align: "center" });
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(107, 114, 128);
        doc.text(label, x + (colW - 2) / 2, y + 13, { align: "center" });
      });
      y += 22;
    }

    // ── SECTION 5: 7-DAY FORECAST TABLE ─────────────────────
    if (forecast.length > 0) {
      // new page if not enough space
      if (y > pageH - 80) { doc.addPage(); y = 16; }

      y = sectionHeader(doc, "5. AI 7-DAY HEAT FORECAST", y, pageW);

      const cols  = ["Day", "Date", "Temp", "Condition", "Heat Risk", "Confidence"];
      const cWs   = [18, 30, 20, 42, 28, 28];
      const rowH  = 8;

      // Table header
      doc.setFillColor(226, 232, 240);
      doc.rect(14, y, pageW - 28, rowH, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(31, 41, 55);
      let cx = 16;
      cols.forEach((col, i) => { doc.text(col, cx, y + 5.5); cx += cWs[i]; });
      y += rowH;

      // Table rows
      forecast.forEach((row, idx) => {
        if (y > pageH - 20) { doc.addPage(); y = 16; }
        if (idx % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(14, y, pageW - 28, rowH, "F");
        }
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(31, 41, 55);
        cx = 16;
        const cells = [
          row.day,
          row.date,
          `${row.temperature}°C`,
          row.predicted ? "AI Prediction" : (row.condition ?? ""),
          row.heat_risk,
          `${row.confidence}%`,
        ];
        cells.forEach((cell, i) => {
          // colour the risk cell
          if (i === 4) {
            const c = RISK_RGB[row.heat_risk] || [107, 114, 128];
            doc.setTextColor(...c);
            doc.setFont("helvetica", "bold");
          }
          doc.text(String(cell), cx, y + 5.5);
          doc.setTextColor(31, 41, 55);
          doc.setFont("helvetica", "normal");
          cx += cWs[i];
        });
        // row border
        doc.setDrawColor(226, 232, 240);
        doc.line(14, y + rowH, pageW - 14, y + rowH);
        y += rowH;
      });
      y += 8;
    }

    // ── SECTION 6: NEARBY HOSPITALS NOTE ────────────────────
    if (y > pageH - 30) { doc.addPage(); y = 16; }
    y = sectionHeader(doc, "6. NEARBY HOSPITALS", y, pageW);
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    doc.text("Live hospital data is available in the Nearby Hospitals section of the dashboard.", 14, y);
    doc.text("Use the dashboard to view hospitals within 5 km of your current location.", 14, y + 6);
    y += 18;

    // ── FOOTER ───────────────────────────────────────────────
    const totalPages = doc.internal.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      doc.setFillColor(241, 245, 249);
      doc.rect(0, pageH - 12, pageW, 12, "F");
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(
        "Satellite-Based El Niño Heat Monitoring System  |  AI-Generated Report  |  For informational purposes only.",
        pageW / 2, pageH - 5, { align: "center" }
      );
      doc.text(`Page ${p} of ${totalPages}`, pageW - 14, pageH - 5, { align: "right" });
    }

    doc.save(`heat-report-${city.toLowerCase().replace(/\s+/g, "-")}-${now.toISOString().slice(0, 10)}.pdf`);
  };

  return (
    <div className="card">
      <h2 className="section-title">📄 Download Report</h2>
      <p style={{ fontSize: "14px", color: "var(--text-muted)", marginBottom: "16px" }}>
        Download a professional AI-generated PDF report including weather data, heat risk assessment,
        7-day forecast, analytics summary, and recommendations.
      </p>
      <button className="download-btn" onClick={handleDownload} disabled={!weather?.city}>
        ⬇️ Download AI Report
      </button>
      {!weather?.city && (
        <p style={{ fontSize: "13px", color: "var(--text-muted)", marginTop: "10px" }}>
          Search for a city first to generate the report.
        </p>
      )}
    </div>
  );
}
